### ISSUE TITLE
Some colors are not updated

### ISSUE THREAD

**Issue by ivanalmasi** [bigpick/em-client#1]
Hi, thanks for creating this theme. I am using it for few days now and there seems to be only some minor issue. Color for selected item in sidebars (both left and right) is not updated to Dracula theme.

It can be seen on your screenshot, but I also highlighted it here, please check.

![image](https://user-images.githubusercontent.com/8042325/127827921-ab1bce44-12a1-4b14-afcf-46f8a990ac09.png)

**Comment by bigpick** [comment]
Hey @ivanalmasi ! No problem - sorry you had to wait for so long to get your request implemented.

As for the selected buttons - I've reloaded the eM Client application after having previously selected the Dracula theme, and they are not present for me (I just have not updated the screenshots yet). I.e:

![image](https://user-images.githubusercontent.com/9803299/127882046-74246436-0749-4e9b-8d09-ec1fdafd4ed7.png)

Notice - no blue bar along the bottom. If you completely close the eM Client application and then re-open after having selected the Dracula theme, do they still exist for you? 

Thanks!

**Comment by bigpick** [comment]
I just updated the repo's screenshots - that is how it should appear.

**Comment by ivanalmasi** [comment]
> Hey @ivanalmasi ! No problem - sorry you had to wait for so long to get your request implemented.

No worries at all, thanks for spending time on it.

> Notice - no blue bar along the bottom. If you completely close the eM Client application and then re-open after having selected the Dracula theme, do they still exist for you?

You are right, it looks fine after restarting.
